import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import type { FileSnapshot } from '../src/core/contracts.js';
import { extractFile } from '../src/extractors/index.js';
import { formatForPath } from '../src/discovery/policy.js';

const fixtureRoot = fileURLToPath(new URL('./fixtures/phase1/', import.meta.url));
const fixtures = ['safety.md', 'safety.ts', 'safety.go', 'safety.rs', 'safety.py', 'Safety.java'];

describe('Phase 1 extractors', () => {
  it('maps every editable span back to its exact original UTF-8 bytes', async () => {
    for (const name of fixtures) {
      const bytes = await readFile(path.join(fixtureRoot, name));
      const source = bytes.toString('utf8');
      const format = formatForPath(name);
      expect(format).toBeDefined();
      const snapshot: FileSnapshot = { id: `f_${name.replace(/\W/gu, '_')}`, path: name,
        sha256: createHash('sha256').update(bytes).digest('hex'), format: format!, byteLength: bytes.length,
        encoding: 'utf8', bom: false, eol: 'lf' };
      const result = await extractFile(source, snapshot, ['AST']);
      expect(result.segments.length, name).toBeGreaterThan(0);
      for (const segment of result.segments) {
        expect(segment.sourceMap).toHaveLength(1);
        const range = segment.sourceMap[0]!.source;
        expect(bytes.subarray(range.startByte, range.endByte).toString('utf8'), name).toBe(segment.editableText);
      }
    }
  });

  it('keeps directives, strings, code examples, doctests, and Markdown destinations outside editable text', async () => {
    const extracted: string[] = [];
    for (const name of fixtures) {
      const bytes = await readFile(path.join(fixtureRoot, name));
      const format = formatForPath(name)!;
      const snapshot: FileSnapshot = { id: `f_${name.replace(/\W/gu, '_')}`, path: name, sha256: 'a'.repeat(64),
        format, byteLength: bytes.length, encoding: 'utf8', bom: false, eol: 'lf' };
      extracted.push(...(await extractFile(bytes.toString('utf8'), snapshot, [])).segments.map(segment => segment.editableText));
    }
    const prose = extracted.join('\n');
    for (const protectedText of ['strings are protected', 'example code', 'protected doctest', 'https://example.com/a',
      'spellagent-disable', 'Code generated by example', '#cgo', 'protected snippet']) {
      expect(prose).not.toContain(protectedText);
    }
  });
});
