import { mkdtemp, mkdir, readFile, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { configSchema } from '../src/core/contracts.js';
import { discover } from '../src/discovery/discover.js';

const config = configSchema.parse({ provider: { name: 'openai', model: 'offline-test' }, exclude: ['custom-generated/**'] });

describe('Phase 1 discovery', () => {
  it('applies exclusions to walks and explicit paths without consulting Git metadata', async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), 'spellagent-discovery-'));
    await mkdir(path.join(root, '.git'));
    await mkdir(path.join(root, '.hidden'));
    await mkdir(path.join(root, 'custom-generated'));
    await writeFile(path.join(root, '.git', 'config'), 'must not be read');
    await writeFile(path.join(root, '.hidden', 'notes.md'), 'Hidden prose.');
    await writeFile(path.join(root, 'custom-generated', 'plain.java'), '// Generated prose.');
    await writeFile(path.join(root, 'file.pb.go'), 'package fixture\n// Generated prose.\n');
    await writeFile(path.join(root, 'README.md'), '# Heading\n\nEligible prose.\n');
    await writeFile(path.join(root, 'generated.rs'), '// @generated by fixture\npub fn x() {}\n');
    await symlink(path.join(root, 'README.md'), path.join(root, 'linked.md'));
    const result = await discover({ root, paths: [], config });
    expect(result.files.map(file => file.snapshot.path)).toEqual(['README.md']);
    expect(result.skipped).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: '.git', reason: 'mandatory_directory' }),
      expect.objectContaining({ path: '.hidden', reason: 'hidden_path' }),
      expect.objectContaining({ path: 'custom-generated', reason: 'config_exclude' }),
      expect.objectContaining({ path: 'file.pb.go', reason: 'generated_path' }),
      expect.objectContaining({ path: 'generated.rs', reason: 'generated_marker' }),
      expect.objectContaining({ path: 'linked.md', reason: 'symlink' }),
    ]));
    expect(await readFile(path.join(root, '.git', 'config'), 'utf8')).toBe('must not be read');
    const explicit = await discover({ root, paths: ['file.pb.go'], config });
    expect(explicit.files).toHaveLength(0);
    expect(explicit.skipped[0]).toMatchObject({ reason: 'generated_path' });
  });
});
