import { mkdtemp, mkdir, readFile, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { preferencesSchema } from '../src/core/contracts.js';
import { discover } from '../src/discovery/discover.js';

const preferences = preferencesSchema.parse({ schemaVersion: 2, exclude: ['custom-generated/**'] });
const roots: string[] = [];
afterEach(async () => { for (const root of roots.splice(0)) await rm(root, { recursive: true, force: true }); });

describe('migrated discovery protection fixtures', () => {
  it('applies exclusions to walks and explicit paths without consulting Git metadata', async () => {
    const root = await realpath(await mkdtemp(path.join(os.tmpdir(), 'spellagent-discovery-')));
    roots.push(root);
    await mkdir(path.join(root, '.git'));
    await mkdir(path.join(root, '.hidden'));
    await mkdir(path.join(root, 'custom-generated'));
    await writeFile(path.join(root, '.git', 'config'), 'must not be read');
    await writeFile(path.join(root, '.hidden', 'notes.md'), 'Hidden prose.');
    await writeFile(path.join(root, 'custom-generated', 'plain.java'), '// Generated prose.');
    await writeFile(path.join(root, 'file.pb.go'), 'package fixture\n// Generated prose.\n');
    await writeFile(path.join(root, 'README.md'), '# Heading\n\nEligible prose.\n');
    await writeFile(path.join(root, 'generated.rs'), '// @generated by fixture\npub fn x() {}\n');
    await symlink(path.join(root, 'README.md'), path.join(root, 'linked.md'));
    const result = await discover({ root, paths: [], preferences });
    expect(result.filter(item => item.state === 'eligible').map(item => item.path)).toEqual(['README.md']);
    expect(result).toEqual(expect.arrayContaining([
      expect.objectContaining({ path: '.git', code: 'mandatory_directory' }),
      expect.objectContaining({ path: '.hidden', code: 'hidden_path' }),
      expect.objectContaining({ path: 'custom-generated', code: 'config_exclude' }),
      expect.objectContaining({ path: 'file.pb.go', code: 'generated_path' }),
      expect.objectContaining({ path: 'generated.rs', code: 'generated_marker' }),
      expect.objectContaining({ path: 'linked.md', code: 'symlink' }),
    ]));
    expect(await readFile(path.join(root, '.git', 'config'), 'utf8')).toBe('must not be read');
    const explicit = await discover({ root, paths: ['file.pb.go'], preferences });
    expect(explicit).toEqual([{ path: 'file.pb.go', pathType: 'unknown', state: 'skipped', code: 'generated_path' }]);
  });
});
