import { createHash } from 'node:crypto';
import { lstat, readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { relativePathSchema, type Config, type FileSnapshot, type Segment } from '../core/contracts.js';
import { actualCommentTexts } from '../extractors/code.js';
import { extractFile } from '../extractors/index.js';
import { markdownCommentTexts } from '../extractors/markdown.js';
import type { ExtractionDiagnostic } from '../extractors/types.js';
import type { CodeLanguage } from '../extractors/parsers.js';
import { compileGlobs, firstGlobMatch } from './globs.js';
import { formatForPath, mandatoryPathReason, generatedPathRule, type SupportedFormat } from './policy.js';
import { resolveRequestedPath, UserError } from './config.js';

export type SkipReason =
  | 'hidden_path' | 'mandatory_directory' | 'mandatory_file' | 'credential_file' | 'generated_path'
  | 'generated_marker' | 'config_exclude' | 'not_included' | 'unsupported_format' | 'symlink'
  | 'too_large' | 'binary' | 'invalid_utf8' | 'unsafe_path' | 'read_failed' | 'parse_failed';
export type SkippedPath = { path: string; reason: SkipReason; detail?: string };
export type DiscoveredFile = { snapshot: FileSnapshot; source: string; segments: Segment[]; diagnostics: ExtractionDiagnostic[]; notices: string[] };
export type DiscoveryResult = { files: DiscoveredFile[]; skipped: SkippedPath[]; failed: SkippedPath[] };

const generatedMarkers: readonly { id: string; regex: RegExp }[] = [
  { id: 'go_do_not_edit', regex: /^[ \t]*(?:<!--[ \t]*)?(?:(?:\/[/!*]|\*|#)[ \t]*)?Code generated .+ DO NOT EDIT\.[ \t]*(?:\*\/|-->)?[ \t]*$/imu },
  { id: 'protoc_banner', regex: /^[ \t]*(?:<!--[ \t]*)?(?:(?:\/[/!*]|\*|#)[ \t]*)?Generated by the protocol buffer compiler\.?[ \t]*(?:\*\/|-->)?[ \t]*$/imu },
  { id: 'generated_annotation', regex: /^[ \t]*(?:<!--[ \t]*)?(?:(?:\/[/!*]|\*|#)[ \t]*)?@generated\b.*?(?:-->)?[ \t]*$/imu },
  { id: 'auto_generated_region', regex: /<auto-generated\s*\/?\s*>/iu },
];

function normalizedPath(root: string, absolute: string): string {
  return path.relative(root, absolute).split(path.sep).join('/');
}

function markerIn(comments: readonly { text: string; start: number }[], source: string) {
  for (const comment of comments) {
    for (const marker of generatedMarkers) {
      const match = marker.regex.exec(comment.text);
      if (match) {
        const line = source.slice(0, comment.start + match.index).split(/\r\n|\r|\n/u).length;
        return { id: marker.id, line };
      }
    }
  }
  return undefined;
}

async function generatedMarker(source: string, format: SupportedFormat) {
  const comments = format === 'markdown' ? markdownCommentTexts(source) : await actualCommentTexts(source, format as CodeLanguage);
  return markerIn(comments, source);
}

function eolStyle(source: string): FileSnapshot['eol'] {
  const crlf = (source.match(/\r\n/gu) ?? []).length;
  const bare = source.replaceAll('\r\n', '');
  const lf = (bare.match(/\n/gu) ?? []).length;
  const cr = (bare.match(/\r/gu) ?? []).length;
  const kinds = Number(crlf > 0) + Number(lf > 0) + Number(cr > 0);
  if (kinds === 0) return 'none';
  if (kinds > 1) return 'mixed';
  return crlf ? 'crlf' : lf ? 'lf' : 'cr';
}

async function enumerate(requested: readonly string[], cwd: string, root: string, config: Config,
  exclude: ReturnType<typeof compileGlobs>, skipped: SkippedPath[]) {
  const found = new Set<string>();
  const visit = async (absolute: string): Promise<void> => {
    const relative = normalizedPath(root, absolute);
    let info: Awaited<ReturnType<typeof lstat>>;
    try { info = await lstat(absolute); }
    catch (error) { throw new UserError(`Cannot inspect ${relative || '.'}: ${(error as Error).message}`); }
    if (info.isSymbolicLink()) { if (relative) skipped.push({ path: relative, reason: 'symlink' }); return; }
    if (info.isDirectory()) {
      if (relative) {
        const reason = mandatoryPathReason(relative, config.includeHidden);
        if (reason) { skipped.push({ path: relative, reason: reason as SkipReason }); return; }
        const excluded = firstGlobMatch(relative, exclude) ?? firstGlobMatch(`${relative}/__spellagent_descendant__`, exclude);
        if (excluded) { skipped.push({ path: relative, reason: 'config_exclude', detail: excluded }); return; }
      }
      const entries = await readdir(absolute, { withFileTypes: true });
      for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name, 'en'))) await visit(path.join(absolute, entry.name));
    } else if (info.isFile() && relative) found.add(relative);
  };
  if (requested.length === 0) {
    await visit(root);
  } else {
    for (const input of requested) await visit(resolveRequestedPath(input, cwd, root));
  }
  return [...found].sort((a, b) => a.localeCompare(b, 'en'));
}

export async function discover(options: { root: string; cwd?: string; paths: readonly string[]; config: Config }): Promise<DiscoveryResult> {
  const cwd = options.cwd ?? options.root;
  const skipped: SkippedPath[] = [];
  const failed: SkippedPath[] = [];
  let include: ReturnType<typeof compileGlobs>;
  let exclude: ReturnType<typeof compileGlobs>;
  try {
    include = compileGlobs(options.config.include);
    exclude = compileGlobs(options.config.exclude);
  } catch (error) {
    throw new UserError(`Invalid scope glob: ${(error as Error).message}`);
  }
  const paths = await enumerate(options.paths, cwd, options.root, options.config, exclude, skipped);
  const files: DiscoveredFile[] = [];
  for (const relative of paths) {
    if (!relativePathSchema.safeParse(relative).success) { skipped.push({ path: relative, reason: 'unsafe_path' }); continue; }
    const mandatory = mandatoryPathReason(relative, options.config.includeHidden);
    if (mandatory) {
      const detail = generatedPathRule(relative);
      skipped.push(detail === undefined ? { path: relative, reason: mandatory as SkipReason } : { path: relative, reason: mandatory as SkipReason, detail });
      continue;
    }
    const excluded = firstGlobMatch(relative, exclude);
    if (excluded) { skipped.push({ path: relative, reason: 'config_exclude', detail: excluded }); continue; }
    const format = formatForPath(relative);
    if (!format) { skipped.push({ path: relative, reason: 'unsupported_format' }); continue; }
    if (!firstGlobMatch(relative, include)) { skipped.push({ path: relative, reason: 'not_included' }); continue; }
    const absolute = path.join(options.root, ...relative.split('/'));
    let bytes: Buffer;
    try { bytes = await readFile(absolute); }
    catch (error) { failed.push({ path: relative, reason: 'read_failed', detail: (error as NodeJS.ErrnoException).code ?? 'unknown' }); continue; }
    if (bytes.length > options.config.limits.maxFileBytes) { skipped.push({ path: relative, reason: 'too_large', detail: String(bytes.length) }); continue; }
    if (bytes.includes(0)) { skipped.push({ path: relative, reason: 'binary' }); continue; }
    try { new TextDecoder('utf-8', { fatal: true }).decode(bytes); }
    catch { skipped.push({ path: relative, reason: 'invalid_utf8' }); continue; }
    const source = bytes.toString('utf8');
    let marker;
    try { marker = await generatedMarker(source, format); }
    catch { failed.push({ path: relative, reason: 'parse_failed', detail: 'generated_marker_classification' }); continue; }
    if (marker) { skipped.push({ path: relative, reason: 'generated_marker', detail: `${marker.id}:line_${marker.line}` }); continue; }
    const sha256 = createHash('sha256').update(bytes).digest('hex');
    const snapshot: FileSnapshot = { id: `f_${createHash('sha256').update(relative).digest('hex').slice(0, 20)}`, path: relative,
      sha256, format, byteLength: bytes.length, encoding: 'utf8', bom: bytes.subarray(0, 3).equals(Buffer.from([0xef, 0xbb, 0xbf])), eol: eolStyle(source) };
    const extraction = await extractFile(source, snapshot, options.config.glossary);
    if (extraction.diagnostics.some(item => item.code === 'parse_error' || item.code === 'parse_failed')) {
      failed.push({ path: relative, reason: 'parse_failed' }); continue;
    }
    files.push({ snapshot, source, ...extraction });
  }
  return { files, skipped: skipped.sort((a, b) => a.path.localeCompare(b.path, 'en')), failed: failed.sort((a, b) => a.path.localeCompare(b.path, 'en')) };
}
