import { createHash } from 'node:crypto';
import { readdir } from 'node:fs/promises';
import path from 'node:path';
import { MAX_FILE_BYTES, relativePathSchema, type Preferences, type FileSnapshot } from '../core/contracts.js';
import { HelperError } from '../core/errors.js';
import { actualCommentTexts } from '../extractors/code.js';
import { extractFile } from '../extractors/index.js';
import { markdownCommentTexts } from '../extractors/markdown.js';
import type { CodeLanguage } from '../extractors/parsers.js';
import { prepareSegments } from '../plugin/paging.js';
import { compileGlobs, firstGlobMatch } from './globs.js';
import { formatForPath, mandatoryPathReason, type SupportedFormat } from './policy.js';
import { assertChain, inspectPath, readLocalFile, strictUtf8, targetPath } from './filesystem.js';

export const sha256 = (value: string | Buffer) => createHash('sha256').update(value).digest('hex');
const order = (a: string, b: string) => a < b ? -1 : a > b ? 1 : 0;
export type DiscoveryEntry = {
  path: string; state: 'eligible' | 'skipped' | 'failed'; code?: string;
  snapshot?: FileSnapshot;
  coverage?: { extractedSegments: number; eligibleSegments: number; skippedSegments: number; diagnostics: number; notices: number };
};

const generatedMarkers: readonly { id: string; regex: RegExp }[] = [
  { id: 'go_do_not_edit', regex: /^[ \t]*(?:<!--[ \t]*)?(?:(?:\/[/!*]|\*|#)[ \t]*)?Code generated .+ DO NOT EDIT\.[ \t]*(?:\*\/|-->)?[ \t]*$/imu },
  { id: 'protoc_banner', regex: /^[ \t]*(?:<!--[ \t]*)?(?:(?:\/[/!*]|\*|#)[ \t]*)?Generated by the protocol buffer compiler\.?[ \t]*(?:\*\/|-->)?[ \t]*$/imu },
  { id: 'generated_annotation', regex: /^[ \t]*(?:<!--[ \t]*)?(?:(?:\/[/!*]|\*|#)[ \t]*)?@generated\b.*?(?:-->)?[ \t]*$/imu },
  { id: 'auto_generated_region', regex: /<auto-generated\s*\/?\s*>/iu },
];

function markerIn(comments: readonly { text: string; start: number }[], source: string) {
  for (const comment of comments) {
    for (const marker of generatedMarkers) {
      const match = marker.regex.exec(comment.text);
      if (match) {
        const line = source.slice(0, comment.start + match.index).split(/\r\n|\r|\n/u).length;
        return { id: marker.id, line };
      }
    }
  }
  return undefined;
}

async function generatedMarker(source: string, format: SupportedFormat) {
  const comments = format === 'markdown' ? markdownCommentTexts(source) : await actualCommentTexts(source, format as CodeLanguage);
  return markerIn(comments, source);
}

function eolStyle(source: string): FileSnapshot['eol'] {
  const crlf = (source.match(/\r\n/gu) ?? []).length;
  const bare = source.replaceAll('\r\n', '');
  const lf = (bare.match(/\n/gu) ?? []).length;
  const cr = (bare.match(/\r/gu) ?? []).length;
  const kinds = Number(crlf > 0) + Number(lf > 0) + Number(cr > 0);
  if (kinds === 0) return 'none';
  if (kinds > 1) return 'mixed';
  return crlf ? 'crlf' : lf ? 'lf' : 'cr';
}

export function pathPolicy(relative: string, preferences: Preferences): string | undefined {
  if (!relativePathSchema.safeParse(relative).success) return 'unsafe_path';
  const mandatory = mandatoryPathReason(relative, preferences.includeHidden);
  if (mandatory) return mandatory;
  const exclusions = compileGlobs(preferences.exclude);
  const parts = relative.split('/');
  for (let length = 1; length <= parts.length; length += 1) {
    const prefix = parts.slice(0, length).join('/');
    const ancestorPolicy = mandatoryPathReason(prefix, preferences.includeHidden);
    if (ancestorPolicy) return ancestorPolicy;
    if (firstGlobMatch(prefix, exclusions)) return 'config_exclude';
    if (length < parts.length && firstGlobMatch(`${prefix}/`, exclusions)) return 'config_exclude';
  }
  return undefined;
}

export async function extractLocalFile(root: string, relative: string, preferences: Preferences) {
  const policy = pathPolicy(relative, preferences);
  if (policy) throw new HelperError(policy);
  const format = formatForPath(relative);
  if (!format) throw new HelperError('unsupported_format');
  if (!firstGlobMatch(relative, compileGlobs(preferences.include))) throw new HelperError('not_included');
  const bytes = await readLocalFile(targetPath(root, relative), MAX_FILE_BYTES);
  if (bytes.includes(0)) throw new HelperError('binary');
  const source = strictUtf8(bytes);
  let marker;
  try { marker = await generatedMarker(source, format); }
  catch { throw new HelperError('parse_failed'); }
  if (marker) throw new HelperError('generated_marker');
  const snapshot: FileSnapshot = { id: `f_${sha256(relative).slice(0, 20)}`, path: relative,
    sha256: sha256(bytes), format, byteLength: bytes.length, encoding: 'utf8',
    bom: bytes.subarray(0, 3).equals(Buffer.from([0xef, 0xbb, 0xbf])), eol: eolStyle(source) };
  const extraction = await extractFile(source, snapshot, preferences.glossary);
  if (extraction.diagnostics.some(item => item.code === 'parse_error' || item.code === 'parse_failed')) {
    throw new HelperError('parse_failed');
  }
  const prepared = prepareSegments(extraction.segments);
  return { snapshot, source, ...extraction, prepared,
    coverage: { extractedSegments: extraction.segments.length,
      eligibleSegments: prepared.filter(item => item.kind === 'segment').length,
      skippedSegments: prepared.filter(item => item.kind === 'skipped').length,
      diagnostics: extraction.diagnostics.length, notices: extraction.notices.length },
  };
}

const skips = new Set(['hidden_path', 'mandatory_directory', 'mandatory_file', 'credential_file', 'generated_path',
  'generated_marker', 'config_exclude', 'not_included', 'unsupported_format', 'symlink', 'hard_link',
  'too_large', 'binary', 'invalid_utf8', 'unsafe_path', 'not_regular_file']);
function failure(relative: string, error: unknown): DiscoveryEntry {
  const code = error instanceof HelperError ? error.code : 'read_failed';
  return { path: relative, state: skips.has(code) ? 'skipped' : 'failed', code };
}

// Reconstruct a source-free manifest on each request. Only one source file is
// held for extraction at a time; no snapshots or preview results reach disk.
export async function discover(options: { root: string; paths: readonly string[]; preferences: Preferences }) {
  const entries = new Map<string, DiscoveryEntry>();
  const visited = new Set<string>();
  const rootIdentity = await inspectPath(options.root);
  const visit = async (relative: string, depth: number): Promise<void> => {
    if (visited.has(relative)) return;
    visited.add(relative);
    if (visited.size > 100_000 || depth > 128) throw new HelperError('scope_too_large');
    const policy = relative === '.' ? undefined : pathPolicy(relative, options.preferences);
    if (policy) { entries.set(relative, { path: relative, state: 'skipped', code: policy }); return; }
    const absolute = targetPath(options.root, relative);
    let inspected;
    try { inspected = await inspectPath(absolute); }
    catch (error) { entries.set(relative, failure(relative, error)); return; }
    if (inspected.info.isDirectory()) {
      if (relative !== '.' && firstGlobMatch(`${relative}/`, compileGlobs(options.preferences.exclude))) {
        entries.set(relative, { path: relative, state: 'skipped', code: 'config_exclude' }); return;
      }
      let names: string[];
      try {
        names = await readdir(absolute);
        if (names.length + visited.size > 100_000) throw new HelperError('scope_too_large');
        await assertChain(inspected.chain);
      } catch (error) {
        if (error instanceof HelperError && error.code === 'scope_too_large') throw error;
        entries.set(relative, failure(relative, error)); return;
      }
      for (const name of names.sort(order)) await visit(relative === '.' ? name : `${relative}/${name}`, depth + 1);
      return;
    }
    if (!inspected.info.isFile()) {
      entries.set(relative, { path: relative, state: 'skipped', code: 'not_regular_file' }); return;
    }
    try {
      const file = await extractLocalFile(options.root, relative, options.preferences);
      entries.set(relative, { path: relative, state: 'eligible', snapshot: file.snapshot, coverage: file.coverage });
    } catch (error) { entries.set(relative, failure(relative, error)); }
  };
  for (const relative of [...new Set(options.paths.length ? options.paths : ['.'])].sort(order)) await visit(relative, 0);
  await assertChain(rootIdentity.chain);
  return [...entries.values()].sort((a, b) => order(a.path, b.path));
}
